global:

services:
  - frontend:
    type: nodejs
    agent: yes
  - backend:
    type: nodejs
    agent: yes
  - ext-payment-1:
    type: nodejs
    agent: no
  - ext-payment-2:
    type: nodejs
    agent: no
  - backend-db:
    type: mysql

transactions:
- http://frontend/cart/checkout:
  - http://tracking/checkout
  - http://backend/checkout:
    - scheme: http
      host: [ ext-payment-1, ext-payment-2 ]
      path: /pay
- http://frontend/cart/add:
  - http://backend/cartadd:
    - sql://backend-db
