global:
  machine: true
  netviz: true
  loaders: true
  services: true

apm:
  controller: http://localhost:8090
  accountName: customer1
  accountAccessKey:
  applicationName: apm_game
  eventsService: http://localhost:9080
  globalAccountName:
  eum:
    appKey:
    adrumExtUrlHttp: http://cdn.appdynamics.com
    adrumExtUrlHttps: https://cdn.appdynamics.com
    beaconUrlHttp: http://col.eum-appdynamics.com
    beaconUrlHttps: https://col.eum-appdynamics.com

services:
  frontend:
    type: nodejs
    labels:
      version: 1.0
      dc: WEST
    agent: yes
    port: 3000
    endpoints:
      http:
        /checkout:
          - http://backend/cart/checkout
          - cache,128
          - image,http://cdn/logo.png
          - script,http://cdn/scrips.js
        /addtocart:
          - [http://backend/cart/add, http://backend-v2/cart/add, http://backend-v3/cart/add]
          - image,http://cdn/logo.png
  backend:
    type: java
    agent: yes
    port: 3009
    endpoints:
      http:
        /cart/checkout:
          - cache,1024
          - - call: http://ext-payment-1/pay
              remoteTimeout: 2000
            - call: http://ext-payment-2/pay
              remoteTimeout: 2000
            - call: http://ext-payment-3/pay
              remoteTimeout: 2000
            - call: http://ext-payment-1/pay
              remoteTimeout: 2000
            - call: http://ext-payment-2/pay
              remoteTimeout: 2000
            - call: http://ext-payment-1/pay
              remoteTimeout: 2000
        /cart/add:
          - cache,128
          - call: slow,800
            probability: 0.1
          - image,http://cdn/logo.png
          - call: data
            id: price
            type: double
            value: [1,2,3]
  backend-v2:
    type: java
    agent: yes
    port: 3010
    endpoints:
      http:
        /cart/add:
          - sql://backend-db/shop?query=INSERT INTO carts(name,value) VALUES("test","123")
          - call: slow,800
            probability: 0.5
          - image,http://cdn/logo.png
  backend-v3:
    type: php
    agent: yes
    port: 3007
    endpoints:
      http:
        /cart/add:
          - sql://backend-db/shop?query=INSERT INTO carts(name,value) VALUES("test","123")
          - call: slow,800
            probability: 0.5
          - image,http://cdn/logo.png
  ext-payment:
    type: nodejs
    agent: no
    aliases: [ext-payment-1, ext-payment-2]
    endpoints:
      http:
        pay:
          - call: sleep,8000
            schedule: "* */2 * * * * *"
          - call: error,500,Oopsi
            schedule: "* */3 * * * * *"
          - sleep,500
  ext-payment-3:
    type: nodejs
    agent: no
    port: 3001
    endpoints:
      http:
        pay:
          - call: error,500,Payment failed
            probability: 0.5
          - sleep,3000
  cdn:
    type: nodejs
    agent: no
    port: 3002
    options:
      connectionDelay: 5000
    endpoints:
      http:
        logo.png:
          - sleep,1200
  backend-db:
    type: mysql
    databases:
      shop:
        carts: [id, name, value]
        customers: [id, name, email]


loaders:
  browser:
    type: puppeteer
    wait: 15
    count: 5
    urls:
      - http://frontend/addtocart
      - http://frontend/addtocart
      - http://frontend/checkout
