apm:
  controller: http://osxltsneum.fritz.box:8090
  accountName: customer1
  accountAccessKey: ca6b2b9a-d391-412b-a5c4-c65e744d2b0f
  applicationName: apm_game_2
  eventsService: http://osxltsneum.fritz.box:9080
  globalAccountName: customer1_bc537d78-f54a-4253-a0c0-4c4d3196c872

services:
  frontend:
    type: nodejs
    agent: yes
    port: 3000
    endpoints:
      http:
        /checkout:
          - http://backend/cart/checkout
          - mail://send
        /addtocart:
          - http://backend/cart/add
  backend:
    type: java
    agent: yes
    endpoints:
      http:
        /cart/checkout:
          - sql://backend-db/?query=SELECT * from carts
          - [http://ext-payment-1/pay, http://ext-payment-2/pay, http://ext-payment-3/pay]
        /cart/add:
          - sql://backend-db/?query=SELECT * from carts
  ext-payment:
    type: nodejs
    agent: no
    aliases: [ext-payment-1, ext-payment-2]
    endpoints:
      http:
        pay:
          - sleep,500
  ext-payment-3:
    type: nodejs
    agent: no
    port: 3001
    endpoints:
      http:
        pay:
          - sleep,3000
  backend-db:
    type: mysql
    tables:
      carts: [id, owner, value]
    disabled: true

loaders:
  simple:
    type: curl
    urls:
      - http://frontend/addtocart
      - http://frontend/addtocart
      - http://frontend/checkout
