apm:
  controller: http://osxltsneum.fritz.box:8090
  accountName: customer1
  accountAccessKey: 4b4c0344-64ba-4777-a3ac-10b143910367
  applicationName: apm_game
  eventsService: http://osxltsneum.fritz.box:9080
  globalAccountName: customer1_1fbb87ca-d377-45a9-9643-9904bceee0f0
  eum:
    appKey: 'AD-AAB-AAK-RUM'
    adrumExtUrlHttp: 'http://cdn.appdynamics.com'
    adrumExtUrlHttps: 'https://cdn.appdynamics.com'
    beaconUrlHttp: 'http://col.eum-appdynamics.com'
    beaconUrlHttps: 'https://col.eum-appdynamics.com'

services:
  shop:
    type: nodejs
    agent: yes
    endpoints:
      /homepage:
        - slow,1000
        - image,http://cdn/logo.png
      /addtocart:

      /cartpage:

  frontend:
    type: nodejs
    agent: yes
    port: 3000
    endpoints:
      http:
        /checkout:
          - http://backend/cart/checkout
          - mail://send
          - image,http://cdn/logo.png
        /addtocart:
          - [http://backend/cart/add, http://backend-v2/cart/add]
          - image,http://cdn/logo.png
  backend:
    type: java
    agent: yes
    endpoints:
      http:
        /cart/checkout:
          - sql://backend-db/?query=SELECT * from carts
          - [http://ext-payment-1/pay, http://ext-payment-2/pay, http://ext-payment-3/pay, http://ext-payment-1/pay, http://ext-payment-2/pay, http://ext-payment-1/pay]

        /cart/add:
          - sql://backend-db/?query=SELECT * from carts
          - call: slow,800
            probability: 0.1
          - image,http://cdn/logo.png
  backend-v2:
    type: java
    agent: yes
    endpoints:
      http:
        /cart/add:
          - sql://backend-db/?query=SELECT * from carts
          - call: slow,800
            probability: 0.5
          - image,http://cdn/logo.png
  ext-payment:
    type: nodejs
    agent: no
    aliases: [ext-payment-1, ext-payment-2]
    endpoints:
      http:
        pay:
          - sleep,500
  ext-payment-3:
    type: nodejs
    agent: no
    port: 3001
    endpoints:
      http:
        pay:
          - call: error,500,Payment failed
            probability: 0.5
          - sleep,3000
  cdn:
    type: nodejs
    agent: no
    port: 3002
    endpoints:
      http:
        logo.png:
          - sleep,1200
  backend-db:
    type: mysql
    tables:
      carts: [id, owner, value]
    disabled: true

loaders:
  browser:
    type: phantomjs
    wait: 15
    count: 2
    adrumTimeout: 5
    urls:
      - http://frontend/addtocart
      - http://frontend/addtocart
      - http://frontend/checkout
